version: '3'

tasks:
  default:
    cmds:
      - task: test

  npm:install:
    desc: Runs npm install
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json

  build:
    desc: Build project using esbuild
    deps: [npm:install]
    cmds:
      - npm run build
    sources:
      - ./src/**/*.js
      - package.json
      - package-lock.json
    generates:
      - bin/index.js

  test:
    desc: Run tests
    deps: [npm:install]
    cmds:
      - npm run test

  publish:
    desc: Publish release to npm
    deps: [build]
    cmds:
      - npm publish --access=public

  clean:
    desc: Clean build files
    cmds:
      - rm -rf bin/
